config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars do
      resources :bookings, shallow: true
    end
  get '/search', to: "cars#search", as: :search
get '/profile', to: 'profile#show'
get '/profile/my_cars', to: 'profile#cars'
get '/profile/my_bookings', to: 'profile#bookings'
get '/profile/my_trips', to: 'profile#trips'
get '/profile/:id/edit', to: 'profile#edit', as: :edit_profile
patch '/profile/:id', to: 'profile#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :photos, dependent: :destroy
  validates :brand, presence: true
  validates :color, presence: true
  validates :year, presence: true, numericality: true
  validates :model, presence: true
  validates :location, presence: true
  validates :title, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  # before_save :val_coords

  accepts_nested_attributes_for :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PhotoUploader
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :authenticate_user!, except: [:home, :cars, :car, :search]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
   # For additional fields in app/views/devise/registrations/new.html.erb
   # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :avatar_url])
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :phone_number, :photo])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :phone_number, :photo])


 end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    set_booking
    @car = @booking.car
    @renter = @booking.user
  end

  def update
    set_booking
    @booking.validated = true
    @booking.save
    redirect_to booking_path(@booking.id)
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to profile_my_trips_path(@booking)
    else
      render "cars/show"
    end
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to profile_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all

    @cars = Car.where.not(latitude: nil, longitude: nil)
    @markers = @cars.map do |car|
      {
        lng: car.longitude,
        lat: car.latitude,
        infoWindow: { content: render_to_string(partial: "/cars/map_window", locals: { car: car }) }
      }
    end
  end

  def new
    @car = Car.new
    @user = current_user
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      if params[:car][:photos] == nil
      else
        params[:car][:photos].each do |photo|
          @car.photos.create(picture: photo)
        end
      end
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def search
    if params[:query]
      sql_query = "location ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query][:location]}%").order("created_at DESC")
      @params = search_params
    else
      @cars = Car.where.not(latitude: nil, longitude: nil)
      @cars = Car.all.order('created_at DESC')
    end
    
    @markers = @cars.map do |car|
      {
        lng: car.longitude,
        lat: car.latitude,
        infoWindow: { content: render_to_string(partial: "/cars/map_window", locals: { car: car }) }
      }
    end
  end

  def show
    @booking = Booking.new
    set_car
    if params[:query]
      @starts_at = search_params[:starts_at]
      @ends_at = search_params[:ends_at]
      @booking.start_date = @starts_at
      @booking.end_date = @ends_at
    end
    @car.user = current_user
  end

  def edit
    set_car
  end

  def update
    set_car
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    set_car
    @car.destroy
    redirect_to profile_my_cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :color, :year, :model, :location, :title, :price, :url, photos_attributes: [:id, :car_id, :picture])
  end

  def search_params
    params.require(:query).permit(:starts_at, :ends_at)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :set_user, only: [:show, :cars, :bookings, :trips, :edit]

  def show
  end

  def cars
    @cars = @user.cars
  end

  def bookings
    @cars = @user.cars
    @bookings = @cars.map {|car| car.bookings }.flatten

  end

  def trips
    @bookings = @user.bookings
  end

  def edit
    # raise
    set_user
  end

  def update
    set_user
    @user.update(user_params)
    redirect_to profile_path(@user)
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<!-- Need to raise an error if current user different from owner / renter -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">

<div class="booking-container-new", style="margin: 20px;">
  <div class="booking-info" style="background-color: gray; border-radius: 5px;">
    <h2 style="font-size: 20px;">Info about the Booking</h2>
    <br>
    <br>
    <p style="font-weight: bold; color: black;"><i class="fa fa-calendar"></i>  Starts: <%=  @booking.start_date%></p>
    <p style="font-weight: bold; color: black;"><i class="fa fa-calendar"></i>  Starts: <%=  @booking.end_date%></p>
    <p style="font-weight: bold;">Booking Status :
      <% if @booking.validated %>
      <span style="color:green">Validated</span>
      <% else %>
      <span style="color:red">Pending</span>
      <% end %>
    </p>
    <% if current_user == @car.user  %>
    <%= link_to "Accept Booking", booking_path(@booking.id), method: :patch %> <br>
    <%= link_to "Decline Booking", booking_path(@booking.id), method: :delete %>
    <% else %>
    <%= link_to "Cancel Booking", booking_path(@booking.id), method: :delete %><br>
    <%= link_to "Back to My Bookings", profile_my_trips_path %>
    <% end %>
  </div>
  <div class="car-details">

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width:200px;">
    <div class="carousel-inner">
      <div class="carousel-item active">
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
    <h2>Info about the car</h2>
    <%= @car.color.capitalize %>
    <%= @car.model %>
    <%= @car.brand %><br>
    Year: <%= @car.year %><br>
    Location: <%= @car.location %>
  </div>
</div>
</div>

app/views/cars/_map_window.html.erb
<%= car.model %>
<%= car.brand %>
<%= car.price %>
<%= car.location %>

app/views/cars/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">
  <div id="container" class= "banner-photo-show" style='text-align: center'>
    <h1> Edit your Car</h1>
    <div  style="text-align:center;" >
      <ul style="list-style: none;"  >

        <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<h1>Cars in your Location</h1>

<br>

<div>
  <%= link_to "Add a new Car", new_car_path, class: "btn btn-primary"%>
</div>

<br>

<div class="container">
  <div class="row">

    <% @cars.each do |car| %>
    <%= link_to car_path(car) do  %>
    <div class="col-xs-12 col-md-6">
    <% if car.photos.first == nil  %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.cookandreevesvans.com/static/img/default-car.jpg');">
      <% else %>
      <% photo = cl_image_path car.photos.first.picture, height: 175, crop: :fill  %>
    <% end  %>

      <div class="card-category">
        <h4><%= car.location%></h4>
      </div>
      <br>
      <div class="row">
        <% @cars.each do |car| %>
        <div class="col-xs-12 col-sm-6 col-md-6">

          <%= link_to car_path(car) do  %>
          <!-- <div class="col-xs-12 col-sm-6 col-md-4""> -->
            <% if car.photos.first == nil  %>
            <% photo = 'http://www.cookandreevesvans.com/static/img/default-car.jpg' %>
            <% else %>
            <% photo = cl_image_path car.photos.first.picture, height: 175, crop: :fill  %>
            <% end  %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= photo %>')">
              <div class="card-category">
                <h5><%= car.location%></h5>
              </div>
              <div class="card-description">
                <h2><%= car.brand %></h2>
                <p><%= car.model%></p>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<%= render "shared/form" %>

app/views/cars/search.html.erb
<div class="banner index" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">
  <div class="flex-container">
    <div class="cards-container">
      <div class="row">
        <!-- <div class="col-sm-4"> -->
      <h2 class="h2_search">Search Results</h2>
          <% @cars.each do |car| %>
          <div class="col-xs-12 col-md-6 col-md-6">
            <%= link_to car_path(car, query: @params) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://i.kinja-img.com/gawker-media/image/upload/s--N9dSzhBR--/c_scale,f_auto,fl_progressive,q_80,w_800/h69z8tw0lyq9b8txhupw.jpg');">
              <div class="card-category">
                <h5><%= car.location%></h5>
              </div>
              <div class="card-description">
                <h2><%= car.brand %></h2>
                <p><%= car.model %></p>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

      <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">
<h1> Vehicle to be Booked:</h1>
  <div class="box">
    <div class="dates">
      <% if @booking.start_date == nil %>
      <% else %>
      <div class="form-border">
        <div class="form-car-dates">
          <%= simple_form_for [@car, @booking] do |b| %>
          <%= b.input :start_date, :as => :hidden, :input_html => { :value => localize(b.object.start_date) } %>
          <%= b.input :end_date, :as => :hidden, :input_html => { :value => localize(b.object.end_date) } %>
          <h4 id="book_btn">Your desired booking dates begin on <strong><%= @starts_at %></strong> and end on <strong><%=@ends_at %></strong></h4><br>
          <h4>Please confirm your booking</h4>
          <%= b.submit "Confirm Booking", class: "btn btn-primary" %>
          <% end %>
          or<br>
              <div class="btn text-center">
            <%= link_to "Continue Browsing", search_path, class: "btn btn-primary" %>
          </div>
        </div>

      </div>
      <% end %>
    </div>
        <% if @car.photos.first == nil  %>
        <img src=""http://www.cookandreevesvans.com/static/img/default-car.jpg"" alt="" class="car-image">
        <% else %>
        <div id="car-image" ><%= cl_image_tag @car.photos.first.picture %></div>
        <% end %>

        <div class="car-model">
          <h2><%= @car.model %></h2>
          <p>_______________________</p>
          <table class="car-info">
              <%= @car.year %> <%= @car.color %> <%= @car.brand %><br> Price: $<%= @car.price %><br> Location: <%= @car.location %>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CarBnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">
  <div class="box">
    <div class="banner-content">
      <p>Get There....while eating breakfast...in bed</p>
        <div class="form-wrapper" style="width: 150px; margin: 0 auto;">
          <%= simple_form_for :query, url: search_path, method: "get" do |f| %>
          <%= f.input :starts_at, placeholder: "dd/mm/yyyy", as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :ends_at, placeholder: "dd/mm/yyyy", as: :string, required: false, input_html: {class: "datepicker"} %>
        </div>
    <div clas="form-wrapper" style="width: 150px; margin: 0 auto;">
      <%= f.input :location, label: "Where", as: :string, placeholder: "Anywhere" %>
      <%= f.button :submit, "Go", class: "search_button" %>
    </div>
          <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright CarBnB
  </div>
</div>

app/views/shared/_form.html.erb
<div class="banner-sing-up" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_6_Hero_CC_BigSur_coast_TS_1280x642_0.jpg');">


<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4"><h2>Add a new car</h2>
      <%= simple_form_for @car do |f| %>
      <div class="col-sm-offset-4 col-sm-4">
        <%= f.input :title %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :year %>
        <%= f.input :color %>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.file_field  :photos, multiple: true %>
        <div class="form-actions">
          <%= f.button :submit, "Sign up", class: "search_button" %>
        </div>
        <% end %>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "carlogo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <div class="navbar-wagon-item navbar-wagon-link">
    <%= link_to "Add a new car", new_car_path, class: "add_car_button" %>
    <% if current_user == nil %>
      <%= link_to "Sign Up", new_user_registration_path, class: "sign_up_button" %>
      <%= link_to "Sign In", new_user_session_path, class: "sign_in_button" %>
    <% else %>

      </div>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

        <% if current_user.photo.blank? %>
        <%= cl_image_tag "user-login-icon-14",  {id: "navbar-wagon-menu", class: "avatar dropdown-toggle", data: {toggle: :dropdown}} %>

        <% else %>
        <!-- <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <%= cl_image_tag current_user.photo,  {id: "navbar-wagon-menu", class: "avatar dropdown-toggle", data: {toggle: :dropdown}} %>
        <!-- </div> -->
        <% end %>

    <% end  %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "My Profile", profile_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>